// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmlMVHAKHTLVOvg6TwYpokuEIiS7grtIE',
    appId: '1:43216823113:web:9d9742cdd064b134127098',
    messagingSenderId: '43216823113',
    projectId: 'tiktok-reels-2c388',
    authDomain: 'tiktok-reels-2c388.firebaseapp.com',
    storageBucket: 'tiktok-reels-2c388.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdpm5MNyBSvHYWOjEbbc-nSHxeAw0rVeM',
    appId: '1:43216823113:android:c3f1657253df99a9127098',
    messagingSenderId: '43216823113',
    projectId: 'tiktok-reels-2c388',
    storageBucket: 'tiktok-reels-2c388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZABWseea1LZkIPXnneVmUtcKgF685jRY',
    appId: '1:43216823113:ios:0aafd5e80255b33d127098',
    messagingSenderId: '43216823113',
    projectId: 'tiktok-reels-2c388',
    storageBucket: 'tiktok-reels-2c388.firebasestorage.app',
    iosBundleId: 'com.example.tiktokDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZABWseea1LZkIPXnneVmUtcKgF685jRY',
    appId: '1:43216823113:ios:0aafd5e80255b33d127098',
    messagingSenderId: '43216823113',
    projectId: 'tiktok-reels-2c388',
    storageBucket: 'tiktok-reels-2c388.firebasestorage.app',
    iosBundleId: 'com.example.tiktokDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmlMVHAKHTLVOvg6TwYpokuEIiS7grtIE',
    appId: '1:43216823113:web:a9db400718af3a42127098',
    messagingSenderId: '43216823113',
    projectId: 'tiktok-reels-2c388',
    authDomain: 'tiktok-reels-2c388.firebaseapp.com',
    storageBucket: 'tiktok-reels-2c388.firebasestorage.app',
  );
}
